### ISSUE TITLE
Compiler error "No known class method for selector 'withConfigName:'"

### ISSUE THREAD

**Issue by xcodewarrier** [appsquickly/Typhoon-example#29]
Within PFCoreComponents.m, line 52 returns a compiler error, "No known class method for selector 'withConfigName:'". 

```
- (id)config
{
    return [TyphoonDefinition withConfigName:@"Configuration.plist"];
}

```

**Comment by nickynick** [comment]
Should be fixed now, thanks for the catch! A bunch of Typhoon headers were reorganized today, and in this particular file the internal ones were imported for some reason.
