### ISSUE TITLE
Support NSStoryboard on OSX

### ISSUE THREAD

**Issue by rsbw** [appsquickly/Typhoon-example#31]
TyphoonStoryboard does not support NSStoryboard on OSX (MacOS)

**Comment by jasperblues** [comment]
This is the iOS example app. Maybe you meant to open an issue on the main repo?

**Comment by rsbw** [comment]
ouh, yes

**Comment by jasperblues** [comment]
k, let's move it there thanks :)

**Comment by rsbw** [comment]
ok
